"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Lead = { id:number; name:string; company:string; email:string; value:number; stage:string; nextAction:string; dueDate:string|null; source:string };
type Project = { id:number; title:string; clientName:string; type:string; description:string; imageUrl:string; status:string; price:number; deadline:string|null; progress:number; published:boolean; websiteUrl:string };
type Task = { id:number; title:string; projectId:number|null; status:string; priority:string; dueDate:string|null };
type Inquiry = { id:number; name:string; email:string; company:string; budget:string; message:string; status:string; createdAt:string };
type Data = { leads:Lead[]; projects:Project[]; tasks:Task[]; inquiries:Inquiry[] };
const empty:Data = { leads:[], projects:[], tasks:[], inquiries:[] };
const tabs = [["pulpit","Pulpit"],["zapytania","Zapytania"],["sprzedaz","Sprzedaż"],["projekty","Projekty"],["zadania","Zadania"]];
const leadStages = ["Nowy kontakt","Brief","Oferta","Decyzja","Realizacja","Zakończony","Utracony"];
const projectStages = ["Planowanie","Treści","Projekt graficzny","Wdrożenie","Testy","Opublikowany","Opieka"];

export default function StudioClient({ ownerEmail }:{ ownerEmail:string }) {
  const [data,setData] = useState<Data>(empty);
  const [tab,setTab] = useState("pulpit");
  const [loading,setLoading] = useState(true);
  const [notice,setNotice] = useState("");
  const load = useCallback(async()=>{ setLoading(true); const res=await fetch("/api/studio",{cache:"no-store"}); if(res.ok) setData(await res.json()); setLoading(false); },[]);
  useEffect(()=>{load()},[load]);
  const kpi = useMemo(()=>({ pipeline:data.leads.filter(x=>!["Zakończony","Utracony"].includes(x.stage)).reduce((s,x)=>s+x.value,0), active:data.projects.filter(x=>!["Opublikowany","Opieka"].includes(x.status)).length, newInquiries:data.inquiries.filter(x=>x.status==="Nowe").length, urgent:data.tasks.filter(x=>x.status!=="Gotowe"&&x.priority==="Pilne").length }),[data]);
  async function create(entity:string, form:HTMLFormElement){ const payload=Object.fromEntries(new FormData(form)); const res=await fetch("/api/studio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity,...payload,published:payload.published==="on"})}); if(res.ok){form.reset();flash("Zapisano");await load()} else flash("Nie udało się zapisać"); }
  async function patch(entity:string,id:number,changes:Record<string,unknown>){ const res=await fetch(`/api/studio/${entity}/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)}); if(res.ok){flash("Zaktualizowano");await load()} }
  async function remove(entity:string,id:number){ if(!confirm("Usunąć ten rekord?"))return; const res=await fetch(`/api/studio/${entity}/${id}`,{method:"DELETE"}); if(res.ok){flash("Usunięto");await load()} }
  function flash(text:string){setNotice(text);setTimeout(()=>setNotice(""),1800)}
  if(loading) return <main className="studio-loading">Ładuję zaplecze Zielonej Marki…</main>;
  return <main className="studio-app">
    <aside className="studio-sidebar"><Link className="brand" href="/"><span className="footer-logo-plate"><img className="brand-logo" src="/logo.png" alt="" /></span><span>ZIELONA<br/>MARKA</span></Link><nav>{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{id==="pulpit"?"⌂":id==="zapytania"?"↗":id==="sprzedaz"?"◎":id==="projekty"?"▦":"✓"}</span>{label}{id==="zapytania"&&kpi.newInquiries>0?<b>{kpi.newInquiries}</b>:null}</button>)}</nav><div className="studio-account"><small>Zalogowany właściciel</small><span>{ownerEmail}</span><form method="post" action="/api/studio/session"><input type="hidden" name="_action" value="logout"/><button type="submit">Wyloguj</button></form></div></aside>
    <div className="studio-content"><header><div><span className="section-no">ZAPLECZE OPERACYJNE</span><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><Link href="/">Podgląd strony ↗</Link></header>{notice&&<div className="toast">{notice}</div>}
      {tab==="pulpit"&&<Dashboard data={data} kpi={kpi} setTab={setTab}/>} 
      {tab==="zapytania"&&<Inquiries rows={data.inquiries} patch={patch} remove={remove}/>} 
      {tab==="sprzedaz"&&<Leads rows={data.leads} create={create} patch={patch} remove={remove}/>} 
      {tab==="projekty"&&<Projects rows={data.projects} create={create} patch={patch} remove={remove}/>} 
      {tab==="zadania"&&<Tasks rows={data.tasks} projects={data.projects} create={create} patch={patch} remove={remove}/>} 
    </div>
  </main>;
}

function Dashboard({data,kpi,setTab}:{data:Data;kpi:{pipeline:number;active:number;newInquiries:number;urgent:number};setTab:(x:string)=>void}){return <><section className="admin-kpis"><article><span>Pipeline sprzedaży</span><b>{kpi.pipeline.toLocaleString("pl-PL")} zł</b><small>{data.leads.length} kontaktów</small></article><article><span>Aktywne projekty</span><b>{kpi.active}</b><small>{data.projects.filter(x=>x.published).length} w portfolio</small></article><article><span>Nowe zapytania</span><b>{kpi.newInquiries}</b><button onClick={()=>setTab("zapytania")}>Otwórz skrzynkę →</button></article><article><span>Pilne zadania</span><b>{kpi.urgent}</b><button onClick={()=>setTab("zadania")}>Zobacz zadania →</button></article></section><section className="admin-two"><div className="admin-card"><div className="admin-head"><div><span className="section-no">TERAZ</span><h2>Projekty w toku</h2></div><button onClick={()=>setTab("projekty")}>Wszystkie</button></div>{data.projects.filter(x=>!["Opublikowany","Opieka"].includes(x.status)).slice(0,5).map(x=><div className="dash-row" key={x.id}><div><b>{x.title}</b><small>{x.clientName} · {x.status}</small></div><div className="mini-progress"><i style={{width:`${x.progress}%`}}/></div><strong>{x.progress}%</strong></div>)}{!data.projects.length&&<Empty text="Dodaj pierwszy projekt w zakładce Projekty."/>}</div><div className="admin-card"><div className="admin-head"><div><span className="section-no">NAJBLIŻSZE</span><h2>Zadania i terminy</h2></div></div>{data.tasks.filter(x=>x.status!=="Gotowe").slice(0,6).map(x=><div className="dash-row" key={x.id}><span className={`priority ${x.priority.toLowerCase()}`}>{x.priority}</span><div><b>{x.title}</b><small>{x.dueDate||"Bez terminu"}</small></div></div>)}{!data.tasks.length&&<Empty text="Dodaj pierwsze zadanie."/>}</div></section></>}

function Inquiries({rows,patch,remove}:{rows:Inquiry[];patch:Function;remove:Function}){return <section className="admin-card"><div className="admin-head"><div><span className="section-no">SKRZYNKA ZE STRONY</span><h2>Zapytania klientów</h2></div></div><div className="inquiry-grid">{rows.map(x=><article key={x.id} className={x.status==="Nowe"?"new":""}><div className="inquiry-top"><div><b>{x.name}{x.company?` · ${x.company}`:""}</b><a href={`mailto:${x.email}`}>{x.email}</a></div><select value={x.status} onChange={e=>patch("inquiry",x.id,{status:e.target.value})}><option>Nowe</option><option>W kontakcie</option><option>Zamknięte</option></select></div><p>{x.message}</p><footer><span>Budżet: {x.budget||"nie podano"}</span><span>{new Date(x.createdAt).toLocaleDateString("pl-PL")}</span><button onClick={()=>remove("inquiry",x.id)}>Usuń</button></footer></article>)}{!rows.length&&<Empty text="Nowe formularze ze strony pojawią się tutaj."/>}</div></section>}

function Leads({rows,create,patch,remove}:{rows:Lead[];create:Function;patch:Function;remove:Function}){return <><FormCard title="Dodaj kontakt sprzedażowy"><form onSubmit={e=>{e.preventDefault();create("lead",e.currentTarget)}} className="admin-form"><label>Imię<input name="name" required/></label><label>Firma<input name="company" required/></label><label>E-mail<input name="email" type="email"/></label><label>Wartość<input name="value" type="number" min="0"/></label><label>Następny krok<input name="nextAction" defaultValue="Skontaktować się"/></label><label>Termin<input name="dueDate" type="date"/></label><button className="button">Dodaj kontakt <span>+</span></button></form></FormCard><section className="admin-card"><div className="admin-table"><div className="admin-table-head"><span>Klient</span><span>Wartość</span><span>Etap</span><span>Następny krok</span><span/></div>{rows.map(x=><div className="admin-table-row" key={x.id}><div><b>{x.company}</b><small>{x.name} · {x.email}</small></div><strong>{x.value.toLocaleString("pl-PL")} zł</strong><select value={x.stage} onChange={e=>patch("lead",x.id,{stage:e.target.value})}>{leadStages.map(s=><option key={s}>{s}</option>)}</select><input value={x.nextAction} onChange={e=>patch("lead",x.id,{nextAction:e.target.value})}/><button className="icon-button" onClick={()=>remove("lead",x.id)}>×</button></div>)}</div></section></>}

function Projects({rows,create,patch,remove}:{rows:Project[];create:Function;patch:Function;remove:Function}){return <><FormCard title="Dodaj projekt lub realizację"><form onSubmit={e=>{e.preventDefault();create("project",e.currentTarget)}} className="admin-form project-form"><label>Nazwa realizacji<input name="title" required/></label><label>Klient<input name="clientName" required/></label><label>Rodzaj<select name="type"><option>Strona firmowa</option><option>Landing page</option><option>Portfolio</option><option>WordPress</option><option>Prototyp PWA</option><option>Automatyzacja procesu</option></select></label><label>Wartość<input name="price" type="number" min="0"/></label><label>Adres strony<input name="websiteUrl" type="url" placeholder="https://"/></label><label>Miniatura - adres obrazu<input name="imageUrl" type="url" placeholder="https://"/></label><label className="wide">Opis<textarea name="description" rows={2}/></label><label>Termin<input name="deadline" type="date"/></label><label className="publish-check"><input name="published" type="checkbox"/> Od razu pokaż w portfolio</label><button className="button">Dodaj projekt <span>+</span></button></form></FormCard><div className="project-admin-grid">{rows.map(x=><article className="project-admin-card" key={x.id}><div className="project-admin-top"><span>{x.type}</span><label><input type="checkbox" checked={x.published} onChange={e=>patch("project",x.id,{published:e.target.checked})}/> Portfolio</label></div><h3>{x.title}</h3><p>{x.clientName} · {x.price.toLocaleString("pl-PL")} zł</p><div className="project-controls"><select value={x.status} onChange={e=>patch("project",x.id,{status:e.target.value})}>{projectStages.map(s=><option key={s}>{s}</option>)}</select><label>Postęp: {x.progress}%<input type="range" min="0" max="100" step="5" value={x.progress} onChange={e=>patch("project",x.id,{progress:Number(e.target.value)})}/></label></div><footer>{x.websiteUrl?<a href={x.websiteUrl} target="_blank">Otwórz stronę ↗</a>:<span>Brak adresu</span>}<button onClick={()=>remove("project",x.id)}>Usuń</button></footer></article>)}{!rows.length&&<Empty text="Dodaj pierwszy projekt. Możesz od razu opublikować go w portfolio."/>}</div></>}

function Tasks({rows,projects,create,patch,remove}:{rows:Task[];projects:Project[];create:Function;patch:Function;remove:Function}){return <><FormCard title="Dodaj zadanie"><form onSubmit={e=>{e.preventDefault();create("task",e.currentTarget)}} className="admin-form"><label className="wide">Zadanie<input name="title" required/></label><label>Projekt<select name="projectId"><option value="">Bez projektu</option>{projects.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Priorytet<select name="priority"><option>Normalny</option><option>Wysoki</option><option>Pilne</option></select></label><label>Termin<input name="dueDate" type="date"/></label><button className="button">Dodaj zadanie <span>+</span></button></form></FormCard><section className="admin-card task-list">{rows.map(x=><article key={x.id}><button className={`task-check ${x.status==="Gotowe"?"done":""}`} onClick={()=>patch("task",x.id,{status:x.status==="Gotowe"?"Do zrobienia":"Gotowe"})}>✓</button><div><b>{x.title}</b><small>{projects.find(p=>p.id===x.projectId)?.title||"Bez projektu"} · {x.dueDate||"bez terminu"}</small></div><span className={`priority ${x.priority.toLowerCase()}`}>{x.priority}</span><select value={x.status} onChange={e=>patch("task",x.id,{status:e.target.value})}><option>Do zrobienia</option><option>W toku</option><option>Gotowe</option></select><button className="icon-button" onClick={()=>remove("task",x.id)}>×</button></article>)}{!rows.length&&<Empty text="Dodaj zadania do realizacji."/>}</section></>}

function FormCard({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-card form-card"><div className="admin-head"><div><span className="section-no">NOWY REKORD</span><h2>{title}</h2></div></div>{children}</section>}
function Empty({text}:{text:string}){return <div className="admin-empty"><span>○</span><p>{text}</p></div>}
